### ISSUE TITLE
Scripts rendered in different places causes interpretation order error

### ISSUE THREAD

**Issue by igorsantos07** [nineinchnick/edatatables#11]
I've noticed that, while the default files `jquery.dataTables`, `ColReorder` and (optional?) default file `jquery.fnSetFilteringDisplay` are registered with no specific `CClientScript::POS_` constant, `jdatatable` is forced to be rendered in the end of the body tag.

If the default script place is `POS_HEAD` that creates an order error, since some scripts depends on `jdatatable`. I could solve this changing my default `clientScript::defaultScriptFilePosition` to be `POS_END`, so everything is rendered at the bottom, but a plugin should not obligate me to configure my entire environment differently.

However, I cannot guess what could be the best fix for the issue, since there are several scripts scattered through the class and I'm not sure about their usage or dependencies. My best guess would be: "force any datatable script to be rendered at the end, since we would be sure that jquery would be available there as well as the table markup and whatnot".

**Comment by nineinchnick** [comment]
You can override that property for every instance using widgetFactory.
