### ISSUE TITLE
Allow for easier customization of translations

### ISSUE THREAD

**Issue by igorsantos07** [nineinchnick/edatatables#13]
It would be cool to be able to provide a custom message category to EDataTables widget, so we can provide our own translations from a message source instead of having to define `['options' => ['oLanguage'] ]` with the original jquery codes in every widget instantiation.

If you agree with the idea I can send a PR :)

**Comment by nineinchnick** [comment]
You can actually override those labels by setting an `oLanguage` option. It's merged with the defaults.
