### ISSUE TITLE
Some default properties where overriden?

### ISSUE THREAD

**Issue by igorsantos07** [nineinchnick/edatatables#14]
I was implementing a static layout file (HTML+JS) from the design team and noticed I had to explicitly define some default properties from the original jQuery DataTables plugin, namely:

- sPaginationType: 'two_button'
- bJQueryUI: false
- bServerSide: false
- sDom (datatableTemplate): null

My layout files were only defining `oLanguage`, and I had to dig a lot inside the DataTables docs and this extension's sourcecode before discovering what was causing the differences between the original layout and the extension's rendering.

Please, consider leaving those options as default, so new developers will have much less trouble moving from handmade implementations into the extension. It's hard to understand issues when you say the extension is a "drop in" replacement when, in fact, some default options are not the default anymore.

**Comment by nineinchnick** [comment]
Closing this one, will address the issue when updating to 1.10.
