### ISSUE TITLE
Is it possible to enable client-side pagination?

### ISSUE THREAD

**Issue by igorsantos07** [nineinchnick/edatatables#15]
Even though I've put `bServerSide` as false to the extension's options (and thus sorting is now client-side) the pagination is still buggy. It always renders only the available entries for the given page (the first, in the case), and takes that as total number of entries available.

I think there should be a `$serverSide` option in the extension that would:
- handle the `bServerSide` jQuery option
- alter the rendering code to output all rows instead of only those of the current page - leaving pagination to DataTables (client-side), not Yii components (server-side)

**Comment by nineinchnick** [comment]
I'd rather strip down the whole extension than provide more options. I'm closing this for now, we'll see if it's going to be easier after updating to 1.10.
