### ISSUE TITLE
Column Level Search Filter

### ISSUE THREAD

**Issue by nishant-befree** [nineinchnick/edatatables#18]
https://code.google.com/p/jquery-datatables-column-filter/source/checkout
how can we add column filter?

https://code.google.com/p/jquery-datatables-column-filter/wiki/ColumnFilter

https://code.google.com/p/edatatables/issues/detail?id=31

Please advice

**Comment by nineinchnick** [comment]
That's some third party code, please ask a more detailed question or try their repository.
