### ISSUE TITLE
No way to turn off jquery.DataTables.js include!

### ISSUE THREAD

**Issue by WadeShuler** [nineinchnick/edatatables#20]
When trying this plugin, I assumed this would setup (by default with no options defined) the same style of table that DataTables does (with no options) as in this [DataTables Example](http://www.datatables.net/manual/styling/bootstrap-simple.html).

This is not the case, and it seems you have to do hacks to get it working.

I have had to override all the included CSS and JS files, as long as edit the EDataTables.php Class. I had to edit it, to get this extension to stop loading the included jquery.DataTables.js file. It was breaking the pagination of the datatable rendered.

```PHP
EDataTables.php (Line: 554):
$cs->registerScriptFile($baseScriptUrl.'/js/jquery.dataTables'.(YII_DEBUG ? '' : '.min' ).'.js');
```

You could comment this out, but it would break your extensions original functionality. One idea is to maybe have it on/off with the `'registerJUI' => false` option. Or just add a new option like: `'jqueryDataTables' => false`.

**Comment by nineinchnick** [comment]
Why would you disable registering the core lib?
