### ISSUE TITLE
CSS Style in each row based on Database Data.

### ISSUE THREAD

**Issue by goodeath** [nineinchnick/edatatables#25]
When I starts the widget, I use the expression:

`'rowCssClassExpression'=>'$data->id ?"row-open":"row-closed" '`

And it works when the page is loaded direct from server. But, when I use ajax pagination, it's like not exists any rowCssClassExpression property. I was searching in files, and I found the EDataTables Class, and the method getFormattedData() that prints a json for ajax request.

The question is: There is some way to pass CSS classes by ajax like using rowCssClassExpression?

**Comment by nineinchnick** [comment]
You'd have to use some JS callbacks to alter classes after data loaded via AJAX has been rendered. Sorry but I can't give you any more specific example how to do that.

**Comment by goodeath** [comment]
@nineinchnick I edited getFormattedData ($ sEcho) Method in [EDataTables](https://github.com/nineinchnick/edatatables/blob/master/EDataTables.php) Class to return the data that I need together with default json data, so, I used "afterAjaxUpdate " Callback JS like you said. It's working
